/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Component;
import javax.swing.ImageIcon;
import network.SqlLiteConnection;

/**
 *
 * @author Sahtia
 */
public class DashboardScreen extends javax.swing.JFrame {

    /**
     * Creates new form DashboardScreen
     */
    public DashboardScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlMenu = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JButton();
        btnListData = new javax.swing.JButton();
        btnSetting = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 600));

        pnlMain.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        pnlMain.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlMain.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html><p style='text-align: center;'>Selamat Datang di<br>Password Manager Apps</p></html>");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlMain.add(jLabel1, "card2");

        pnlMenu.setBackground(new java.awt.Color(1, 19, 48));
        pnlMenu.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 5));

        btnDashboard.setIcon(new ImageIcon("my-asset/default.png"));
        btnDashboard.setText("<html><font color='white'>Dashboard</font><html>");
        btnDashboard.setBorder(null);
        btnDashboard.setFocusPainted(false);
        btnDashboard.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDashboard.setPreferredSize(new java.awt.Dimension(200, 40));
        btnDashboard.setPressedIcon(new ImageIcon("my-asset/pressed.png"));
        btnDashboard.setRolloverIcon(new ImageIcon("my-asset/hover.png"));
        btnDashboard.setSelectedIcon(new ImageIcon("my-asset/selected.png"));
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });
        pnlMenu.add(btnDashboard);

        btnListData.setIcon(new ImageIcon("my-asset/default.png"));
        btnListData.setText("<html><font color='white'>List Data</font><html>");
        btnListData.setBorder(null);
        btnListData.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnListData.setPreferredSize(new java.awt.Dimension(200, 40));
        btnListData.setPressedIcon(new ImageIcon("my-asset/pressed.png"));
        btnListData.setRolloverIcon(new ImageIcon("my-asset/hover.png"));
        btnListData.setSelectedIcon(new ImageIcon("my-asset/selected.png"));
        btnListData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListDataActionPerformed(evt);
            }
        });
        pnlMenu.add(btnListData);

        btnSetting.setIcon(new ImageIcon("my-asset/default.png"));
        btnSetting.setText("<html><font color='white'>Setting</font><html>");
        btnSetting.setBorder(null);
        btnSetting.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSetting.setPreferredSize(new java.awt.Dimension(200, 40));
        btnSetting.setPressedIcon(new ImageIcon("my-asset/pressed.png"));
        btnSetting.setRolloverIcon(new ImageIcon("my-asset/hover.png"));
        btnSetting.setSelectedIcon(new ImageIcon("my-asset/selected.png"));
        btnSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingActionPerformed(evt);
            }
        });
        pnlMenu.add(btnSetting);

        btnLogout.setIcon(new ImageIcon("my-asset/default.png"));
        btnLogout.setText("<html><font color='white'>Logout</font><html>");
        btnLogout.setBorder(null);
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogout.setPreferredSize(new java.awt.Dimension(200, 40));
        btnLogout.setPressedIcon(new ImageIcon("my-asset/pressed.png"));
        btnLogout.setRolloverIcon(new ImageIcon("my-asset/hover.png"));
        btnLogout.setSelectedIcon(new ImageIcon("my-asset/selected.png"));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        pnlMenu.add(btnLogout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
                    .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
//        SqlLiteConnection.connect();
        this._setSelectedNavigation(new DashboardPanel(), true, false, false);
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnListDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListDataActionPerformed
        this._setSelectedNavigation(new ListDataPanel(), false, true, false);
    }//GEN-LAST:event_btnListDataActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        LoginScreen loginScreen = new LoginScreen();
        loginScreen.setLocationRelativeTo(null);
        loginScreen.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingActionPerformed
        this._setSelectedNavigation(new SettingPanel(), false, false, true);
    }//GEN-LAST:event_btnSettingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardScreen().setVisible(true);
            }
        });
    }
    
    private void _setSelectedNavigation(Object panel, Boolean isDashboard, Boolean isListData, Boolean isSetting){
        pnlMain.removeAll();
        pnlMain.repaint();
        pnlMain.revalidate();
        
        pnlMain.add((Component) panel);
        pnlMain.repaint();
        pnlMain.revalidate();
        
        btnDashboard.setSelected(isDashboard);
        btnListData.setSelected(isListData);
        btnSetting.setSelected(isSetting);
        btnLogout.setSelected(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnListData;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSetting;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlMenu;
    // End of variables declaration//GEN-END:variables

}
